/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#bec6e0",
        "on-background": "#191c1e",
        "on-tertiary-fixed-variant": "#005236",
        "surface-dim": "#d8dadc",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        outline: "#737686",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "primary-container": "#2563eb",
        secondary: "#565e74",
        "surface-container": "#eceef0",
        surface: "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "tertiary-container": "#007d55",
        "on-secondary-container": "#5c647a",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed": "#00174b",
        primary: "#004ac6",
        "surface-container-low": "#f2f4f6",
        "on-primary": "#ffffff",
        tertiary: "#006242",
        "secondary-container": "#dae2fd",
        "primary-fixed-dim": "#b4c5ff",
        "on-surface": "#191c1e",
        "on-tertiary-container": "#bdffdb",
        "outline-variant": "#c3c6d7",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        "inverse-surface": "#2d3133",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eff1f3",
        "surface-tint": "#0053db",
        "inverse-primary": "#b4c5ff",
        "tertiary-fixed": "#6ffbbe",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-primary-container": "#eeefff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-bright": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "secondary-fixed": "#dae2fd",
        "on-surface-variant": "#434655",
        "on-tertiary-fixed": "#002113"
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "sans-serif"],
        heading: ["'Plus Jakarta Sans'", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px"
      },
      boxShadow: {
        soft: "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.03)",
        card: "0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)",
        elevated: "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.04)"
      }
    },
  },
  plugins: [],
}
